version: "3"
services:
  postgres:
    image: hub.hamdocker.ir/postgres:14.4
    container_name: akhi_postgres
    volumes:
    - ./volumes/postgres-data:/var/lib/postgresql/data
    ports:
    - "0.0.0.0:8080:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    restart: always